### ISSUE TITLE
can't run notebook with PythonSlicer (missing wsgi package)

### ISSUE THREAD

**Issue by pieper** [Slicer/SlicerJupyter#39]
It would be more convenient if we could run the jupyter notebook directly out of slicer.  It would mean we could automate some of the installation steps to make it easier to use for training purposes (other modes could still be supported for developers)

I was able to do `pip_install('jupyter')` inside slicer, but when I tried to run the notebook it fails with a missing python package, even though it should be a standard part of the Slicer python package (https://docs.python.org/3.6/library/wsgiref.html).  

```
$ /Volumes/SSD2T/ssdtmp/Slicer.app/Contents/bin/PythonSlicer /Volumes/SSD2T/ssdtmp/Slicer.app/Contents/lib/Python/lib/python3.6/site-packages/jupyter.py notebook
Traceback (most recent call last):
  File "/Volumes/SSD2T/ssdtmp/Slicer.app/Contents/lib/Python/bin/jupyter-notebook", line 5, in <module>
    from notebook.notebookapp import main
  File "/Volumes/SSD2T/ssdtmp/Slicer.app/Contents/lib/Python/lib/python3.6/site-packages/notebook/notebookapp.py", line 76, in <module>
    from .base.handlers import Template404, RedirectWithParams
  File "/Volumes/SSD2T/ssdtmp/Slicer.app/Contents/lib/Python/lib/python3.6/site-packages/notebook/base/handlers.py", line 24, in <module>
    import prometheus_client
  File "/Volumes/SSD2T/ssdtmp/Slicer.app/Contents/lib/Python/lib/python3.6/site-packages/prometheus_client/__init__.py", line 3, in <module>
    from . import exposition
  File "/Volumes/SSD2T/ssdtmp/Slicer.app/Contents/lib/Python/lib/python3.6/site-packages/prometheus_client/exposition.py", line 11, in <module>
    from wsgiref.simple_server import make_server, WSGIRequestHandler
ModuleNotFoundError: No module named 'wsgiref'

```

**Comment by jcfr** [comment]
this module is part of the standard python library: https://docs.python.org/3.6/library/wsgiref.html

May be something is wrong with ... https://github.com/python-cmake-buildsystem/python-cmake-buildsystem

**Comment by jcfr** [comment]
> It would be more convenient if we could run the jupyter notebook directly out of slicer

Now that we have python3, both should be possible.

**Comment by lassoan** [comment]
I've added single-click Jupyter server install and launch in Slicer's Python environment.

@pieper @jcfr Could you try if it works on Mac and Linux?
- Install SlicerJupyter extension
- Go to JupyterKernel module and click on "Start Jupyter server" button: Jupyter notebook client should start in the default web browser (first launch may take 10-15 minutes, as it has to download all Jupyter libraries)
- Create a new notebook with Slicer-4.11 kernel
- Try if auto-complete works: type `slicer.mrmlScene.Get` and press `Tab` key -> completions should appear

**Comment by pieper** [comment]
I tried on a ubuntu 20.04 vm.  

I first had to install Jupyter, which puts it in a place that's not in my PATH, so I needed to change the "Copy to install" command a bit:

```
$ ~/.local/bin/jupyter-kernelspec install /home/pieper/.config/NA-MIC/Extensions-29370/SlicerJupyter/share/Slicer-4.11/qt-loadable-modules/JupyterKernel/Slicer-4.11 --replace --user
[InstallKernelSpec] Installed kernelspec slicer-4.11 in /home/pieper/.local/share/jupyter/kernels/slicer-4.11
```

It appears to have run okay, but when I restart and go to the module I get an error (and the kernel install instructions are still there).

```
pieper@sdp-slicer5:~$ ./Downloads/Slicer-4.11.0-2020-09-15-linux-amd64/Slicer 
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-pieper'
Switch to module:  "Welcome"
Switch to module:  "JupyterKernel"
QIODevice::read (QFile, "/home/pieper/.config/NA-MIC/Extensions-29370/SlicerJupyter/share/Slicer-4.11/qt-loadable-modules/JupyterKernel/Slicer-4.11/kernel-template.json"): device not open
```

The file seems to exist and contents appear be fine:

```
$ ls -l ~/.config/NA-MIC/Extensions-29370/SlicerJupyter/share/Slicer-4.11/qt-loadable-modules/JupyterKernel/Slicer-4.11/kernel-template.json 
-rw-r--r-- 1 pieper pieper 438 Sep 29 18:42 /home/pieper/.config/NA-MIC/Extensions-29370/SlicerJupyter/share/Slicer-4.11/qt-loadable-modules/JupyterKernel/Slicer-4.11/kernel-template.json
```

**Comment by lassoan** [comment]
There should be no need to install Jupyter. If you click "Start jupyter server" then it installs jupyter and all other packages and sets them up and creates and registers the kernelspec.

There should be no need for the scripts (such as "jupyter") either, or putting them on the path, as they are just shortcuts for `python -m (scriptname)`.

Can you try what happens if you just click the Start server button?

**Comment by pieper** [comment]
Sorry, I was using an old Slicer version by mistake.

With the right Slicer, the start server button works!  And `slicer.mrmlScene.Get<Tab>` gives complete options as expected too.  Nice!

**Comment by pieper** [comment]
BTW, I was able to test on linux, but not mac since there seem to be only linux extensions today.

**Comment by pieper** [comment]
Tried with today's preview and extension on mac (10.15.6).

After clicking start server got this in the python console:
```
Python 3.6.7 (default, Sep 29 2020, 23:06:45) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)] on darwin
>>> 
Loading Slicer RC file [/Users/pieper/.slicerrc.py]
Collecting pillow
  Using cached Pillow-7.2.0-cp36-cp36m-macosx_10_10_x86_64.whl (2.2 MB)
Installing collected packages: pillow
  Attempting uninstall: pillow
    Found existing installation: Pillow 7.2.0
    Uninstalling Pillow-7.2.0:
      Successfully uninstalled Pillow-7.2.0
Successfully installed pillow-7.2.0
WARNING: You are using pip version 20.1.1; however, version 20.2.3 is available.
You should consider upgrading via the '/Applications/Slicer 8.app/Contents/bin/./python-real -m pip install --upgrade pip' command.
Collecting jupyter
  Downloading jupyter-1.0.0-py2.py3-none-any.whl (2.7 kB)
Collecting ipywidgets
  Using cached ipywidgets-7.5.1-py2.py3-none-any.whl (121 kB)
Collecting pandas
  Using cached pandas-1.1.2-cp36-cp36m-macosx_10_9_x86_64.whl (10.6 MB)
Collecting ipyevents
  Downloading ipyevents-0.8.0-py2.py3-none-any.whl (123 kB)
Collecting ipycanvas
  Downloading ipycanvas-0.5.1-py2.py3-none-any.whl (77 kB)
Collecting nbconvert
  Downloading nbconvert-6.0.6-py3-none-any.whl (551 kB)
Collecting ipykernel
  Using cached ipykernel-5.3.4-py3-none-any.whl (120 kB)
Collecting qtconsole
  Downloading qtconsole-4.7.7-py2.py3-none-any.whl (118 kB)
Collecting notebook
  Using cached notebook-6.1.4-py3-none-any.whl (9.5 MB)
Collecting jupyter-console
  Downloading jupyter_console-6.2.0-py3-none-any.whl (22 kB)
Collecting ipython>=4.0.0; python_version >= "3.3"
  Using cached ipython-7.16.1-py3-none-any.whl (785 kB)
Collecting widgetsnbextension~=3.5.0
  Using cached widgetsnbextension-3.5.1-py2.py3-none-any.whl (2.2 MB)
Collecting traitlets>=4.3.1
  Using cached traitlets-4.3.3-py2.py3-none-any.whl (75 kB)
Collecting nbformat>=4.2.0
  Using cached nbformat-5.0.7-py3-none-any.whl (170 kB)
Collecting pytz>=2017.2
  Using cached pytz-2020.1-py2.py3-none-any.whl (510 kB)
Collecting python-dateutil>=2.7.3
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Requirement already satisfied: numpy>=1.15.4 in ./Slicer 8.app/Contents/lib/Python/lib/python3.6/site-packages (from pandas) (1.19.1)
Requirement already satisfied: pillow>=6.0 in ./Slicer 8.app/Contents/lib/Python/lib/python3.6/site-packages (from ipycanvas) (7.2.0)
Collecting bleach
  Using cached bleach-3.2.1-py2.py3-none-any.whl (145 kB)
Requirement already satisfied: pygments>=2.4.1 in ./Slicer 8.app/Contents/Extensions-29397/SlicerJupyter/lib/python3.6/site-packages (from nbconvert->jupyter) (2.4.1)
Collecting testpath
  Using cached testpath-0.4.4-py2.py3-none-any.whl (163 kB)
Collecting jupyter-core
  Using cached jupyter_core-4.6.3-py2.py3-none-any.whl (83 kB)
Collecting mistune<2,>=0.8.1
  Using cached mistune-0.8.4-py2.py3-none-any.whl (16 kB)
Collecting entrypoints>=0.2.2
  Using cached entrypoints-0.3-py2.py3-none-any.whl (11 kB)
Processing /Users/pieper/Library/Caches/pip/wheels/46/c4/40/718c6fd14c2129ccaee10e0cf03ef6c4d01d98cad5dbbfda38/pandocfilters-1.4.2-py3-none-any.whl
Collecting defusedxml
  Using cached defusedxml-0.6.0-py2.py3-none-any.whl (23 kB)
Collecting nbclient<0.6.0,>=0.5.0
  Using cached nbclient-0.5.0-py3-none-any.whl (65 kB)
Collecting jupyterlab-pygments
  Downloading jupyterlab_pygments-0.1.2-py2.py3-none-any.whl (4.6 kB)
Collecting jinja2>=2.4
  Using cached Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
Collecting jupyter-client
  Using cached jupyter_client-6.1.7-py3-none-any.whl (108 kB)
Processing /Users/pieper/Library/Caches/pip/wheels/37/a7/db/2d592e44029ef817f3ef63ea991db34191cebaef087a96f505/tornado-6.0.4-cp36-cp36m-macosx_10_13_x86_64.whl
Collecting appnope; platform_system == "Darwin"
  Using cached appnope-0.1.0-py2.py3-none-any.whl (4.0 kB)
Collecting pyzmq>=17.1
  Using cached pyzmq-19.0.2-cp36-cp36m-macosx_10_9_intel.whl (1.4 MB)
Collecting qtpy
  Downloading QtPy-1.9.0-py2.py3-none-any.whl (54 kB)
Collecting ipython-genutils
  Using cached ipython_genutils-0.2.0-py2.py3-none-any.whl (26 kB)
Collecting Send2Trash
  Using cached Send2Trash-1.5.0-py3-none-any.whl (12 kB)
Collecting prometheus-client
  Using cached prometheus_client-0.8.0-py2.py3-none-any.whl (53 kB)
Collecting argon2-cffi
  Using cached argon2-cffi-20.1.0.tar.gz (1.8 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Collecting terminado>=0.8.3
  Using cached terminado-0.9.1-py3-none-any.whl (13 kB)
Collecting prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0
  Using cached prompt_toolkit-3.0.7-py3-none-any.whl (355 kB)
Requirement already satisfied: setuptools>=18.5 in ./Slicer 8.app/Contents/lib/Python/lib/python3.6/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets) (49.2.0)
Collecting decorator
  Using cached decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Requirement already satisfied: jedi>=0.10 in ./Slicer 8.app/Contents/Extensions-29397/SlicerJupyter/lib/python3.6/site-packages (from ipython>=4.0.0; python_version >= "3.3"->ipywidgets) (0.17.0)
Collecting backcall
  Using cached backcall-0.2.0-py2.py3-none-any.whl (11 kB)
Collecting pickleshare
  Using cached pickleshare-0.7.5-py2.py3-none-any.whl (6.9 kB)
Collecting pexpect; sys_platform != "win32"
  Using cached pexpect-4.8.0-py2.py3-none-any.whl (59 kB)
Requirement already satisfied: six in ./Slicer 8.app/Contents/lib/Python/lib/python3.6/site-packages (from traitlets>=4.3.1->ipywidgets) (1.15.0)
Collecting jsonschema!=2.5.0,>=2.4
  Using cached jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
Requirement already satisfied: packaging in ./Slicer 8.app/Contents/lib/Python/lib/python3.6/site-packages (from bleach->nbconvert->jupyter) (20.4)
Collecting webencodings
  Using cached webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Collecting nest-asyncio
  Downloading nest_asyncio-1.4.1-py3-none-any.whl (5.2 kB)
Collecting async-generator
  Using cached async_generator-1.10-py3-none-any.whl (18 kB)
Collecting MarkupSafe>=0.23
  Using cached MarkupSafe-1.1.1-cp36-cp36m-macosx_10_6_intel.whl (18 kB)
Collecting cffi>=1.0.0
  Using cached cffi-1.14.3-2-cp36-cp36m-macosx_10_9_x86_64.whl (176 kB)
Collecting ptyprocess; os_name != "nt"
  Using cached ptyprocess-0.6.0-py2.py3-none-any.whl (39 kB)
Collecting wcwidth
  Using cached wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
Requirement already satisfied: parso>=0.7.0 in ./Slicer 8.app/Contents/Extensions-29397/SlicerJupyter/lib/python3.6/site-packages (from jedi>=0.10->ipython>=4.0.0; python_version >= "3.3"->ipywidgets) (0.7.1)
Collecting attrs>=17.4.0
  Using cached attrs-20.2.0-py2.py3-none-any.whl (48 kB)
Processing /Users/pieper/Library/Caches/pip/wheels/34/13/19/294da8e11bce7e563afee51251b9fa878185e14f4b5caf00cb/pyrsistent-0.17.3-cp36-cp36m-macosx_10_13_x86_64.whl
Collecting importlib-metadata; python_version < "3.8"
  Downloading importlib_metadata-2.0.0-py2.py3-none-any.whl (31 kB)
Requirement already satisfied: pyparsing>=2.0.2 in ./Slicer 8.app/Contents/lib/Python/lib/python3.6/site-packages (from packaging->bleach->nbconvert->jupyter) (2.4.7)
Collecting pycparser
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Collecting zipp>=0.5
  Downloading zipp-3.2.0-py3-none-any.whl (5.1 kB)
Building wheels for collected packages: argon2-cffi
  Building wheel for argon2-cffi (PEP 517): started
  Building wheel for argon2-cffi (PEP 517): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: '/Applications/Slicer 8.app/Contents/bin/./python-real' '/Applications/Slicer 8.app/Contents/lib/Python/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py' build_wheel /var/folders/cn/kmqx4dm17gx4hrllqrmnkbp00000gn/T/tmpnn5vu1de
       cwd: /private/var/folders/cn/kmqx4dm17gx4hrllqrmnkbp00000gn/T/pip-install-0awd12ud/argon2-cffi
  Complete output (27 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.13-x86_64-3.6
  creating build/lib.macosx-10.13-x86_64-3.6/argon2
  copying src/argon2/__init__.py -> build/lib.macosx-10.13-x86_64-3.6/argon2
  copying src/argon2/low_level.py -> build/lib.macosx-10.13-x86_64-3.6/argon2
  copying src/argon2/_ffi_build.py -> build/lib.macosx-10.13-x86_64-3.6/argon2
  copying src/argon2/_password_hasher.py -> build/lib.macosx-10.13-x86_64-3.6/argon2
  copying src/argon2/exceptions.py -> build/lib.macosx-10.13-x86_64-3.6/argon2
  copying src/argon2/_legacy.py -> build/lib.macosx-10.13-x86_64-3.6/argon2
  copying src/argon2/__main__.py -> build/lib.macosx-10.13-x86_64-3.6/argon2
  copying src/argon2/_utils.py -> build/lib.macosx-10.13-x86_64-3.6/argon2
  running build_clib
  building 'argon2' library
  creating build/temp.macosx-10.13-x86_64-3.6
  creating build/temp.macosx-10.13-x86_64-3.6/extras
  creating build/temp.macosx-10.13-x86_64-3.6/extras/libargon2
  creating build/temp.macosx-10.13-x86_64-3.6/extras/libargon2/src
  creating build/temp.macosx-10.13-x86_64-3.6/extras/libargon2/src/blake2
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -pthread -Wall -g -fPIC -msse2 -Iextras/libargon2/src/../include -Iextras/libargon2/src/blake2 -c extras/libargon2/src/argon2.c -o build/temp.macosx-10.13-x86_64-3.6/extras/libargon2/src/argon2.o
  extras/libargon2/src/argon2.c:18:10: fatal error: 'string.h' file not found
  #include <string.h>
           ^~~~~~~~~~
  1 error generated.
  error: command '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for argon2-cffi
Failed to build argon2-cffi
ERROR: Could not build wheels for argon2-cffi which use PEP 517 and cannot be installed directly
WARNING: You are using pip version 20.1.1; however, version 20.2.3 is available.
You should consider upgrading via the '/Applications/Slicer 8.app/Contents/bin/./python-real -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Applications/Slicer 8.app/Contents/Extensions-29397/SlicerJupyter/lib/Slicer-4.11/qt-scripted-modules/JupyterNotebooks.py", line 53, in installRequiredPackages
    slicer.util.pip_install("jupyter ipywidgets pandas ipyevents ipycanvas --no-warn-script-location")
  File "/Applications/Slicer 8.app/Contents/bin/Python/slicer/util.py", line 2569, in pip_install
    _executePythonModule('pip', args)
  File "/Applications/Slicer 8.app/Contents/bin/Python/slicer/util.py", line 2545, in _executePythonModule
    logProcessOutput(proc)
  File "/Applications/Slicer 8.app/Contents/bin/Python/slicer/util.py", line 2517, in logProcessOutput
    raise CalledProcessError(retcode, proc.args, output=proc.stdout, stderr=proc.stderr)
subprocess.CalledProcessError: Command '['/Applications/Slicer 8.app/Contents/bin/../bin/PythonSlicer', '-m', 'pip', 'install', 'jupyter', 'ipywidgets', 'pandas', 'ipyevents', 'ipycanvas', '--no-warn-script-location']' returned non-zero exit status 1.
```

**Comment by lassoan** [comment]
Thank you for testing. Unfortunately, argon-cffi does not have wheels for Python-3.6 on Mac. I'll try to bundle this package on Mac (so that it is built on factory and included in the package).
