### ISSUE TITLE
Shutdown all Slicer Jupyter kernels???

### ISSUE THREAD

**Issue by jumbojing** [Slicer/SlicerJupyter#60]
```python
slicer.util._executePythonModule('jupyter', ['notebook', 'list'])
```

```text
Fatal Python error: initsite: Failed to import the site module
Traceback (most recent call last):
  File "/Applications/Slicer.app/Contents/bin/../lib/Python/lib/python3.6/site.py", line 553, in <module>
    main()
  File "/Applications/Slicer.app/Contents/bin/../lib/Python/lib/python3.6/site.py", line 539, in main
    known_paths = addusersitepackages(known_paths)
  File "/Applications/Slicer.app/Contents/bin/../lib/Python/lib/python3.6/site.py", line 282, in addusersitepackages
    user_site = getusersitepackages()
  File "/Applications/Slicer.app/Contents/bin/../lib/Python/lib/python3.6/site.py", line 258, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/Applications/Slicer.app/Contents/bin/../lib/Python/lib/python3.6/site.py", line 248, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/Applications/Slicer.app/Contents/lib/Python/lib/python3.6/sysconfig.py", line 601, in get_config_var
    return get_config_vars().get(name)
  File "/Applications/Slicer.app/Contents/lib/Python/lib/python3.6/sysconfig.py", line 550, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/Applications/Slicer.app/Contents/lib/Python/lib/python3.6/sysconfig.py", line 421, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
ModuleNotFoundError: No module named '_sysconfigdata_m_darwin_darwin'
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
In  [10]:
Line 1:     

File /Applications/Slicer.app/Contents/bin/Python/slicer/util.py, in _executePythonModule:
Line 2851:  logProcessOutput(proc)

File /Applications/Slicer.app/Contents/bin/Python/slicer/util.py, in logProcessOutput:
Line 2820:  raise CalledProcessError(retcode, proc.args, output=proc.stdout, stderr=proc.stderr)

CalledProcessError: Command '['/Applications/Slicer.app/Contents/bin/../bin/PythonSlicer', '-m', 'jupyter', 'notebook', 'list']' returned non-zero exit status 1.
```

**Comment by jumbojing** [comment]
有没有更好的方法来关闭Slicer Jupyter kernels,避免slicer反复的重启呢?

Is there a better way to shut down the slicer Jupyter kernels to avoid repeated restarts of the slicer?

**Comment by lassoan** [comment]
There are many other ways but a simple one is to open the Jupyter notebook pages from your browser history and shut down Jupyter properly.

**Comment by jumbojing** [comment]
太感谢了!
Thanks!!
