### ISSUE TITLE
Unable to remove SlicerJupyter

### ISSUE THREAD

**Issue by drusmanbashir** [Slicer/SlicerJupyter#75]
Hi I uninstalled SlicerJupyter plugin. I still get the slicer icon in my notebooks:
![slicer](https://user-images.githubusercontent.com/5282314/191048737-26451431-109c-4dd0-8e24-3d42ceaaee49.png)

I have tried the following to no avail:
1. Completely delete slicer
2. Uninstall jupyter notebook (pip, conda both)
3. Remove all folders starting with name jupyter* under my conda/lib/python3.9/site-packages folder
4. Remove my .jupyter folder with all config files.

This has obviously broken by jupyter installation badly, and I am trying to get it back up to work. Meanwhile although the tenacious logo is, the error log as I launch notebook may provide a clue:

```
Failed to run command:
    ['/home/ub/programs/Slicer-4.13/bin/../Slicer', '--no-splash', '--python-code', "connection_file=r'/home/ub/.local/share/jupyter/runtime/kernel-e5b35dd7-66d6-4d07-9321-5695e331b211.json';print('JupyterConnectionFile:['+connection_file+']');slicer.modules.jupyterkernel.startKernel(connection_file);slicer.util.mainWindow().showMinimized()"]
        PATH='/home/ub/programs/Slicer-4.13/bin:/usr/local/cuda-11.6/bin:/home/ub/programs/miniconda3/bin:/home/ub/programs/miniconda3/condabin:/home/ub/.cargo/bin:/home/ub/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
        with kwargs:
    {'stdin': -1, 'stdout': None, 'stderr': None, 'cwd': '/home/ub/Dropbox/code/fran/nbs', 'start_new_session': True}
    
[E 15:57:45.505 NotebookApp] [Errno 2] No such file or directory: '/home/ub/programs/Slicer-4.13/bin/../Slicer'
    Traceback (most recent call last):
      File "/home/ub/programs/miniconda3/lib/python3.9/site-packages/jupyter_client/manager.py", line 75, in wrapper
        out = await method(self, *args, **kwargs)
      File "/home/ub/programs/miniconda3/lib/python3.9/site-packages/jupyter_client/manager.py", line 389, in _async_start_kernel
        await ensure_async(self._launch_kernel(kernel_cmd, **kw))
      File "/home/ub/programs/miniconda3/lib/python3.9/site-packages/jupyter_client/utils.py", line 30, in wrapped
        raise e
      File "/home/ub/programs/miniconda3/lib/python3.9/site-packages/jupyter_client/utils.py", line 27, in wrapped
        return loop.run_until_complete(future)
      File "/home/ub/programs/miniconda3/lib/python3.9/site-packages/nest_asyncio.py", line 89, in run_until_complete
        return f.result()
      File "/home/ub/programs/miniconda3/lib/python3.9/asyncio/futures.py", line 201, in result
        raise self._exception
      File "/home/ub/programs/miniconda3/lib/python3.9/asyncio/tasks.py", line 256, in __step
        result = coro.send(None)
      File "/home/ub/programs/miniconda3/lib/python3.9/site-packages/jupyter_client/manager.py", line 307, in _async_launch_kernel
        connection_info = await self.provisioner.launch_kernel(kernel_cmd, **kw)
      File "/home/ub/programs/miniconda3/lib/python3.9/site-packages/jupyter_client/provisioning/local_provisioner.py", line 204, in launch_kernel
        self.process = launch_kernel(cmd, **scrubbed_kwargs)
      File "/home/ub/programs/miniconda3/lib/python3.9/site-packages/jupyter_client/launcher.py", line 170, in launch_kernel
        raise ex
      File "/home/ub/programs/miniconda3/lib/python3.9/site-packages/jupyter_client/launcher.py", line 158, in launch_kernel
        proc = Popen(cmd, **kwargs)
      File "/home/ub/programs/miniconda3/lib/python3.9/subprocess.py", line 951, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/home/ub/programs/miniconda3/lib/python3.9/subprocess.py", line 1821, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: '/home/ub/programs/Slicer-4.13/bin/../Slicer'
```

I eventually got rid of it by deleting my .local/share/jupyter folder. Whilst I re-construct my jupyter installation, I am sharing my fix with others in a similar situation. Can the devs add the feature in the Slicerjupyter installation command to remove all traces of it?

**Comment by lassoan** [comment]
You can uninstall the `kernelspec` for Slicer with a very similar command that you used to install it. The command is visible in the Jupyter kernel module (at least in current Slicer version).

**Comment by drusmanbashir** [comment]
Thank you. I installed it a while ago, so I may be wrong, but I think i followed the steps below:
```
Install [3D Slicer](https://download.slicer.org/) and launch it
    Install SlicerJupyter extension in Extension Manager (in the application menu choose View/Extension Manager, click Install button of SlicerJupyter, wait for the installation to complete, and click Restart)
    Switch to JupyterKernel module (open the module finder by click the "Search" icon on the toolbar, or hitting Ctrl/Cmd-F, then type its name)
    Click Start Jupyter server button
```
For future installation, can you tell me which similar command are you referring to?

**Comment by lassoan** [comment]
This install command (`jupyter-kernelspec install ...`) is shown in the Jupyter Kernel module in Slicer, in `Jupyter server in external Python environment` section and also an example [in the documentation](https://github.com/Slicer/SlicerJupyter/#install-kernel-manually). Replace `install` by `remove` to remove the kernel specification.

**Comment by drusmanbashir** [comment]
Thank you sir!
